[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "free_uploader"
version = "0.0.1"
dependencies = [
    "Jinja2"
]

[tool.setuptools.package-data]
"free_uploader.resources" = ["*"]
"free_uploader.templates" = ["*"]
